version: 2
registries:
  git-github-com:
    type: git
    url: https://github.com
    username: saminfante
    password: "${{secrets.GIT_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "13:49"
    timezone: US/Central
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: com.alibaba:druid-spring-boot-starter
    versions:
    - 1.2.4
    - 1.2.5
  - dependency-name: com.aliyun.oss:aliyun-sdk-oss
    versions:
    - 3.11.2
    - 3.11.3
  registries:
  - git-github-com
